### ISSUE TITLE
64-bit

### ISSUE THREAD

**Issue by ak0815** [inthekloud/ITK.Instabug#1]
Hello,

I can not create 64-bit build. Log:

Ld build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/x86_64/TEST\ APP normal x86_64
[TRACE] :      cd "/Users/ak/Dropbox/tt2/App/TEST APP/TEST APP 0.0.1/build/iphone"
[TRACE] :      export IPHONEOS_DEPLOYMENT_TARGET=7.0
[TRACE] :      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/build/Debug-iphonesimulator -L/Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/lib -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/itk.instabug/1.1.0 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/ti.jbchart/0.2 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/ti.canvas/1.1.0 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/de.marcelpociot.mwkprogress/1.2 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/ti.charts/1.5.1 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/nl.fokkezb.colorpick/1.0.2 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/de.marcelpociot.circularslider/1.0 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/com.apaladini.blur/1.0.0 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/de.marcelpociot.circularprogress/1.1 -L/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/dk.napp.drawer/1.2.0 -L/Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/Classes/APSAnalytics -L/Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/Classes/APSHTTPClient -F/Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/build/Debug-iphonesimulator -F/Users/andreaskopf/Library/Application\ Support/Titanium/modules/iphone/itk.instabug/1.0.0/platform/iphone -filelist /Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/x86_64/TEST\ APP.LinkFileList -dead_strip -Xlinker -objc_abi_version -Xlinker 2 -ObjC -framework QuartzCore -framework QuartzCore -framework QuartzCore -framework CoreImage -framework QuartzCore -framework CoreImage -framework QuartzCore -framework CoreGraphics -framework UIKit -framework QuartzCore -framework CoreGraphics -framework UIKit -ObjC -framework QuartzCore -ObjC -framework QuartzCore -framework CoreGraphics -framework CoreGraphics /usr/lib/libc++.dylib /usr/lib/libc++.dylib -framework Instabug -framework Foundation -framework QuartzCore -framework SystemConfiguration -framework CoreMotion -framework CoreTelephony -framework AudioToolbox -framework QuartzCore -framework UIKit -framework MessageUI -framework OpenGLES -framework GLKit -framework CoreGraphics /usr/lib/libc++.dylib /usr/lib/libc++.dylib -framework Instabug -framework Foundation -framework QuartzCore -framework SystemConfiguration -framework CoreMotion -framework CoreTelephony -framework AudioToolbox -framework QuartzCore -framework UIKit -framework MessageUI -framework OpenGLES -framework GLKit -framework CoreGraphics -weak_framework iAd -fobjc-link-runtime -Xlinker -no_implicit_dylibs -stdlib=libc++ -mios-simulator-version-min=7.0 -lti_ios_profiler -framework CoreMedia -weak_framework CoreMotion -lAPSAnalytics -weak_framework CoreText -framework EventKit -framework EventKitUI -weak_framework Security -framework Foundation -weak_framework UIKit -framework CoreGraphics -framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -weak_framework MapKit -framework MessageUI -framework MobileCoreServices -lti_ios_debugger -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -lsqlite3 -lz -framework AudioToolbox -lAPSHTTPClient -weak_framework MediaPlayer -framework AVFoundation -lxml2 -framework StoreKit -lTiCore -litk.instabug -lti.jbchart -lti.canvas -lde.marcelpociot.mwkprogress -lti.charts -lnl.fokkezb.colorpick -lde.marcelpociot.circularslider -lcom.apaladini.blur -lde.marcelpociot.circularprogress -ldk.napp.drawer -ltiverify -licucore -Xlinker -dependency_info -Xlinker /Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/x86_64/TEST\ APP_dependency_info.dat -o /Users/ak/Dropbox/tt2/App/TEST\ APP/TEST\ APP\ 0.0.1/build/iphone/build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/x86_64/TEST\ APP
[TRACE] :  ld: warning: directory not found for option '-F/Users/andreaskopf/Library/Application Support/Titanium/modules/iphone/itk.instabug/1.0.0/platform/iphone'
[TRACE] :  ld: framework not found Instabug
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  2015-01-23 09:19:20.361 xcodebuild[37762:3994090]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/andreaskopf/Library/Developer/Xcode/DeveloperPortal%206.1.1.db).
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/i386/TEST\ APP normal i386
[ERROR] :  	Ld build/TEST\ APP.build/Debug-iphonesimulator/TEST\ APP-universal.build/Objects-normal/x86_64/TEST\ APP normal x86_64
[ERROR] :  (2 failures)

**Comment by AhmedTheGeek** [comment]
Try installing the old version using gittio or from the dist folder, and copy it to your titanium modules folder, and then try to build and it should work.

It fails since it's looking for the framework file, and i can't find it, and it supposed to be there: /Users/andreaskopf/Library/Application Support/Titanium/modules/iphone/itk.instabug/1.0.0/platform/iphone

or try to download the 64bit binary from the dist folder version 1.1.0.. :)

**Comment by ak0815** [comment]
Thanks!
